openapi: 3.0.2
servers:
  - url: /api
info:
  title: 'Portfilio API'
  version: 0.0.1
  description: "Portfolio API descirption" 
tags:
  - name: project
    description: Everything about Projects
  - name: user
    description: Operations about user
paths:
  /projects:
    get:
      tags:
        - project
      summary: Get projects from db
      operationId: getProjects
      responses:
        '200':
          description: Successful operation
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectArray'
  '/projects/{projectId}':
    get:
      tags:
        - project
      summary: Find project by ID
      description: Returns a single project
      operationId: getProjectById
      parameters:
        - name: projectId
          in: path
          example: 1
          description: ID of project to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetail'
        '404':
          description: Project not found
components:
  schemas: 
    Project:
      required:
        - title
        - description
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: 'my project'
        description:
          type: string
          example: 'my project'
      type: object
    ProjectDetail:
      required:
        - titleFR
        - titleEN
        - descriptionFR
        - descriptionEN
        - mainPictureUrl
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 10
        titleFR:
          type: string
          example: 'my project'
        titleEN:
          type: string
          example: 'my project'
        descriptionFR:
          type: string
          example: 'my project'
        descriptionEN:
          type: string
          example: 'my project'
        mainPictureUrl:
          type: string
          example: 'https://site.com/img.png'
      type: object
    ProjectArray:
      type: array
      items:
        $ref: '#/components/schemas/Project'
    