name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlexxNB/caprover-action@v1
        with:
          branch: main
          server: '${{ secrets.CAPROVER_SERVER }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: '${{ secrets.CAPROVER_APP_NAME }}'