name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: "Setup mySQL"
        uses: haltuf/mysql-action@master
        with:
          host port: 3306
          mysql database: 'test'
          mysql root password: 'root'
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: |
          npm install
      - name: Reset DB
        run: DATABASE_URL=mysql://root:root@localhost:3306/test npx prisma migrate deploy
      - name: npm install, build
        run: |
          npm install
          DATABASE_URL=mysql://root:root@localhost:3306/test npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}